# Generated by Django 5.0.4 on 2024-06-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0002_alter_content_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            bases=('page.content',),
        ),
    ]
