# Generated by Django 5.0.4 on 2024-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
