# Generated by Django 5.0.4 on 2024-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='tag',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='icon',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
