# Generated by Django 5.0.4 on 2024-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_account_color_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.RemoveField(
            model_name='content',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
