# Generated by Django 5.0.4 on 2024-06-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_content_date_remove_content_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.account'),
        ),
    ]
