# Generated by Django 5.0.6 on 2024-06-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('token', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=30)),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('file', models.IntegerField()),
                ('author_id', models.BigIntegerField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('path', models.FilePathField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
