# Generated by Django 5.0.6 on 2024-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=30)),
                ('redditSize', models.IntegerField(default=10)),
                ('youtubeSize', models.IntegerField(default=10)),
                ('everytimeSize', models.IntegerField(default=10)),
                ('url', models.URLField(default='http://default.url/icon.png')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactDB',
        ),
    ]
