# Generated by Django 5.0.6 on 2024-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatDB',
        ),
        migrations.RemoveField(
            model_name='contentdb',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='contentdb',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contentdb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contentdb',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='contentdb',
            name='time',
        ),
        migrations.RemoveField(
            model_name='filedb',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filedb',
            name='path',
        ),
        migrations.AddField(
            model_name='contentdb',
            name='userID',
            field=models.CharField(default='default_userID', max_length=100),
        ),
        migrations.AddField(
            model_name='contentdb',
            name='userIcon',
            field=models.URLField(default='http://default.url/icon.png'),
        ),
        migrations.AddField(
            model_name='contentdb',
            name='vote',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filedb',
            name='url',
            field=models.URLField(default='http://default.url/icon.png'),
        ),
        migrations.AlterField(
            model_name='contentdb',
            name='image_url',
            field=models.BigIntegerField(default=0),
        ),
    ]
