# Generated by Django 5.0.6 on 2024-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdb',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
