# Generated by Django 5.0.6 on 2024-05-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
