# Generated by Django 5.0.6 on 2024-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformDiscord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
