# Generated by Django 5.0.6 on 2024-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformDiscord', '0002_discordmessage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
