# Generated by Django 5.0.6 on 2024-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformDiscord', '0003_discordmessage_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='author_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
